In [13]:
import pandas as pd
import numpy as np
import os
import csv

# 轉換檔案 (xls -> csv)

In [14]:
import pandas as pd
data_xls_2021 = pd.read_excel(r'2021 蔬菜產品日交易行情.xls', 'Sheet1', index_col=None)
data_xls_2021.to_csv('2021_高麗菜.csv', encoding='utf-8')

data_xls_2022 = pd.read_excel(r'2022 蔬菜產品日交易行情.xls', 'Sheet1', index_col=None)
data_xls_2022.to_csv('2022_高麗菜.csv', encoding='utf-8')

# 把用不到的 row 刪掉 (因為有些是 useless 資料)

In [15]:
import csv

def delete_rows_csv(file_path):
    # find these row (want to delete)
    rows_to_delete = [0,1,2,3] 

    # Get the total number of rows in the CSV file 
    with open(file_path, 'r', newline='',encoding="utf-8") as file:
        reader = csv.reader(file)
        total_rows = sum(1 for row in reader) #in order to delete the last row

    # Add the index of the last row to the rows_to_delete list
    rows_to_delete.append(total_rows - 1)

    # Read the CSV file and filter out rows to delete
    with open(file_path, 'r', newline='',encoding="utf-8") as file:
        reader = csv.reader(file)
        lines = [line for i, line in enumerate(reader) if i not in rows_to_delete]

    # Write the remaining lines back to the CSV file
    with open(file_path, 'w', newline='',encoding="utf-8") as file:
        writer = csv.writer(file)
        writer.writerows(lines)


file_path1 = r'2021_高麗菜.csv'
file_path2 = r'2022_高麗菜.csv'
delete_rows_csv(file_path1)
delete_rows_csv(file_path2)

In [16]:
df1 = pd.read_csv(r'2021_高麗菜.csv')
df2 = pd.read_csv(r'2022_高麗菜.csv')

print(df1.columns)
print(df2.columns)

Index(['3', '日　　期', '市　　場', '產　　品', '上價', '中價', '下價', '平均價(元/公斤)', '增減%',
       '交易量(公斤)', '增減%.1', 'Unnamed: 11'],
      dtype='object')
Index(['3', '日　　期', '市　　場', '產　　品', '上價', '中價', '下價', '平均價(元/公斤)', '增減%',
       '交易量(公斤)', '增減%.1', 'Unnamed: 11'],
      dtype='object')

# 把 useless column 刪掉 和 處理 column 名稱(空白問題)

In [17]:
def fix_columns(df):
    # drop useless columns
    df.drop(labels=['3','Unnamed: 11'],axis='columns',inplace=True)

    new_column_names = {'日　　期': '日期', '市　　場': '市場','產　　品':'產品'}
    df.rename(columns=new_column_names, inplace=True)
    return df

df1 = fix_columns(df1)
df2 = fix_columns(df2)

df1.columns

Index(['日期', '市場', '產品', '上價', '中價', '下價', '平均價(元/公斤)', '增減%', '交易量(公斤)',
       '增減%.1'],
      dtype='object')

In [18]:
def to_year(row):
    y_string = row['日期']
    y_string = y_string[:y_string.find('/')]
    y = int(y_string)+1911
    return y

def to_month(row):
    y_string = row['日期']
    y_string = y_string[y_string.find('/')+1:y_string.rfind('/')]
    return int(y_string)

def to_day(row):
    y_string = row['日期']
    y_string = y_string[y_string.rfind('/')+1:]
    return int(y_string)

df1['year'] = df1.apply(to_year, axis=1)
df1['month'] = df1.apply(to_month, axis=1)
df1['day'] = df1.apply(to_day, axis=1)

df2['year'] = df2.apply(to_year, axis=1)
df2['month'] = df2.apply(to_month, axis=1)
df2['day'] = df2.apply(to_day, axis=1)

In [19]:
df1.head(3)

,日期,市場,產品,上價,中價,下價,平均價(元/公斤),增減%,交易量(公斤),增減%.1,year,month,day
0,110/01/01,109 台北一,LA1 甘藍 初秋,35.1,27.5,18.4,27.2,- 1,189266,+ 26,2021,1,1
1,110/01/02,109 台北一,LA1 甘藍 初秋,33.4,26.0,14.2,25.1,- 8,210707,+ 11,2021,1,2
2,110/01/03,109 台北一,LA1 甘藍 初秋,34.9,28.3,19.8,27.9,+ 11,161135,- 24,2021,1,3

In [20]:
df2.head(3)

,日期,市場,產品,上價,中價,下價,平均價(元/公斤),增減%,交易量(公斤),增減%.1,year,month,day
0,111/01/01,109 台北一,LA1 甘藍 初秋,16.9,12.0,8.8,12.4,0,180408,+ 8,2022,1,1
1,111/01/02,109 台北一,LA1 甘藍 初秋,15.4,11.0,7.8,11.3,- 9,181988,+ 1,2022,1,2
2,111/01/04,109 台北一,LA1 甘藍 初秋,15.0,10.0,6.3,10.2,- 10,203591,+ 12,2022,1,4

In [21]:
df1.dtypes

日期            object
市場            object
產品            object
上價           float64
中價           float64
下價           float64
平均價(元/公斤)    float64
增減%           object
交易量(公斤)        int64
增減%.1         object
year           int64
month          int64
day            int64
dtype: object

In [22]:
df2.dtypes

日期            object
市場            object
產品            object
上價           float64
中價           float64
下價           float64
平均價(元/公斤)    float64
增減%           object
交易量(公斤)        int64
增減%.1         object
year           int64
month          int64
day            int64
dtype: object

In [23]:
from datetime import datetime
def to_day_of_yeaer(row):
    specified_date = datetime(row['year'], row['month'], row['day'])
    day_of_yearr = specified_date.timetuple().tm_yday
    return day_of_yearr

df1['day_of_year'] = df1.apply(to_day_of_yeaer, axis=1)
df2['day_of_year'] = df2.apply(to_day_of_yeaer, axis=1)

In [24]:
df1.to_csv('Train_2021_高麗菜_data_file.csv', index=False)
df2.to_csv('Train_2022_高麗菜_data_file.csv', index=False)

# all function

In [13]:
import pandas as pd
import numpy as np
import os
import csv
from datetime import datetime

# change xls file to csv

In [14]:
data_xls = pd.read_excel(r'2018-2021宜蘭高麗菜日交易行情.xls', 'Sheet1', index_col=None)
data_xls.to_csv('2018-2021_宜蘭_高麗菜日交易行情.csv', encoding='utf-8')

In [15]:
def delete_rows_csv(file_path):
    # find these row (want to delete)
    rows_to_delete = [0,1,2,3] 

    # Get the total number of rows in the CSV file 
    with open(file_path, 'r', newline='',encoding="utf-8") as file:
        reader = csv.reader(file)
        total_rows = sum(1 for row in reader) #in order to delete the last row

    # Add the index of the last row to the rows_to_delete list
    rows_to_delete.append(total_rows - 1)

    # Read the CSV file and filter out rows to delete
    with open(file_path, 'r', newline='',encoding="utf-8") as file:
        reader = csv.reader(file)
        lines = [line for i, line in enumerate(reader) if i not in rows_to_delete]

    # Write the remaining lines back to the CSV file
    with open(file_path, 'w', newline='',encoding="utf-8") as file:
        writer = csv.writer(file)
        writer.writerows(lines)

def fix_columns(df):
    # drop useless columns
    df.drop(labels=['3','Unnamed: 11'],axis='columns',inplace=True)

    new_column_names = {'日　　期': '日期', '市　　場': '市場','產　　品':'產品'}
    df.rename(columns=new_column_names, inplace=True)
    return df

def to_year(row):
    y_string = row['日期']
    y_string = y_string[:y_string.find('/')]
    y = int(y_string)+1911
    return y

def to_month(row):
    y_string = row['日期']
    y_string = y_string[y_string.find('/')+1:y_string.rfind('/')]
    return int(y_string)

def to_day(row):
    y_string = row['日期']
    y_string = y_string[y_string.rfind('/')+1:]
    return int(y_string)

def to_day_of_yeaer(row):
    specified_date = datetime(row['year'], row['month'], row['day'])
    day_of_yearr = specified_date.timetuple().tm_yday
    return day_of_yearr

In [17]:
# delete useless rows
delete_rows_csv(r"2018-2021_宜蘭_高麗菜日交易行情.csv")

In [20]:
df = pd.read_csv(r"2018-2021_宜蘭_高麗菜日交易行情.csv")
df.head(3)

,3,日 期,市 場,產 品,上價,中價,下價,平均價(元/公斤),增減%,交易量(公斤),增減%.1,Unnamed: 11
0,4,107/01/02,260 宜蘭市,LA1 甘藍 初秋,20,15,6,15,- 35,1860,+ 6,0.0
1,5,107/01/03,260 宜蘭市,LA1 甘藍 初秋,20,15,6,15,0,1760,- 5,0.0
2,6,107/01/04,260 宜蘭市,LA1 甘藍 初秋,20,15,6,15,0,1850,+ 5,0.0

In [21]:
fix_columns(df)
df.head(3)

,日期,市場,產品,上價,中價,下價,平均價(元/公斤),增減%,交易量(公斤),增減%.1
0,107/01/02,260 宜蘭市,LA1 甘藍 初秋,20,15,6,15,- 35,1860,+ 6
1,107/01/03,260 宜蘭市,LA1 甘藍 初秋,20,15,6,15,0,1760,- 5
2,107/01/04,260 宜蘭市,LA1 甘藍 初秋,20,15,6,15,0,1850,+ 5

In [22]:
df['year'] = df.apply(to_year, axis=1)
df['month'] = df.apply(to_month, axis=1)
df['day'] = df.apply(to_day, axis=1)

In [23]:
df.head(3)

,日期,市場,產品,上價,中價,下價,平均價(元/公斤),增減%,交易量(公斤),增減%.1,year,month,day
0,107/01/02,260 宜蘭市,LA1 甘藍 初秋,20,15,6,15,- 35,1860,+ 6,2018,1,2
1,107/01/03,260 宜蘭市,LA1 甘藍 初秋,20,15,6,15,0,1760,- 5,2018,1,3
2,107/01/04,260 宜蘭市,LA1 甘藍 初秋,20,15,6,15,0,1850,+ 5,2018,1,4

In [24]:
df['day_of_year'] = df.apply(to_day_of_yeaer, axis=1)
df.head(3)

,日期,市場,產品,上價,中價,下價,平均價(元/公斤),增減%,交易量(公斤),增減%.1,year,month,day,day_of_year
0,107/01/02,260 宜蘭市,LA1 甘藍 初秋,20,15,6,15,- 35,1860,+ 6,2018,1,2,2
1,107/01/03,260 宜蘭市,LA1 甘藍 初秋,20,15,6,15,0,1760,- 5,2018,1,3,3
2,107/01/04,260 宜蘭市,LA1 甘藍 初秋,20,15,6,15,0,1850,+ 5,2018,1,4,4

In [25]:
df.to_csv('all_2018-2021_高麗菜_data_file.csv', index=False)