In [1]:
import pandas as pd
import numpy as np
import os
import csv

In [2]:
import os
dirpath1 = r"2021-宜蘭-觀測站"
dirpath2 = r"2022-宜蘭-觀測站"

print("all csv",os.listdir(dirpath1))
print("all csv",os.listdir(dirpath2))

all csv ['467080-2021-01.csv', '467080-2021-02.csv', '467080-2021-03.csv', '467080-2021-04.csv', '467080-2021-05.csv', '467080-2021-06.csv', '467080-2021-07.csv', '467080-2021-08.csv', '467080-2021-09.csv', '467080-2021-10.csv', '467080-2021-11.csv', '467080-2021-12.csv']
all csv ['467080-2022-01.csv', '467080-2022-02.csv', '467080-2022-03.csv', '467080-2022-04.csv', '467080-2022-05.csv', '467080-2022-06.csv', '467080-2022-07.csv', '467080-2022-08.csv', '467080-2022-09.csv', '467080-2022-10.csv', '467080-2022-11.csv', '467080-2022-12.csv']

In [19]:
def complete_path(dirpath):
    paths = []
    for f in os.listdir(dirpath):
        fullpath = os.path.join(dirpath,f)
        paths.append(fullpath)
    return paths

file_path_2021 = complete_path(dirpath1)
file_path_2022 = complete_path(dirpath2)

In [20]:
print(file_path_2021[0])
print(file_path_2022[0])

2021-宜蘭-觀測站\467080-2021-01.csv
2022-宜蘭-觀測站\467080-2022-01.csv

In [21]:
df1 = pd.read_csv(file_path_2021[0])
df1.head(3)

,觀測時間(day),測站氣壓(hPa),海平面氣壓(hPa),測站最高氣壓(hPa),測站最高氣壓時間(LST),測站最低氣壓(hPa),測站最低氣壓時間(LST),氣溫(℃),最高氣溫(℃),最高氣溫時間(LST),...,日最高紫外線指數,日最高紫外線指數時間(LST),總雲量(0~10),地溫0cm,地溫5cm,地溫10cm,地溫20cm,地溫30cm,地溫50cm,地溫100cm
0,ObsTime,StnPres,SeaPres,StnPresMax,StnPresMaxTime,StnPresMin,StnPresMinTime,Temperature,T Max,T Max Time,...,UVI Max,UVI Max Time,Cloud Amount,TxSoil0cm,TxSoil5cm,TxSoil10cm,TxSoil20cm,TxSoil30cm,TxSoil50cm,TxSoil100cm
1,01,1024.6,1025.6,1027.3,2021/01/01 00:01:00,1022.0,2021/01/01 14:52:00,12.3,14.7,2021/01/01 14:05:00,...,3,2021/01/01 14:00:00,10.0,12.8,13.6,14.1,16.0,14.9,16.9,19.8
2,02,1023.6,1024.6,1025.0,2021/01/02 09:14:00,1022.4,2021/01/02 14:00:00,13.1,13.7,2021/01/02 08:00:00,...,1,2021/01/02 13:00:00,10.0,13.7,14.4,14.7,16.0,15.2,16.6,19.4

In [22]:
# 得到日期
def get_date_from_filename(dirpath):
    csv_file_names_without_csv = []

    for i in dirpath:
        csv_file_names_without_csv.append(i[i.find('-20')+1:i.find('.')])
    return csv_file_names_without_csv

year_month_2021 = get_date_from_filename(file_path_2021)
year_month_2022 = get_date_from_filename(file_path_2022)

In [23]:
print(year_month_2021)
print(year_month_2022)

['2021-01', '2021-02', '2021-03', '2021-04', '2021-05', '2021-06', '2021-07', '2021-08', '2021-09', '2021-10', '2021-11', '2021-12']
['2022-01', '2022-02', '2022-03', '2022-04', '2022-05', '2022-06', '2022-07', '2022-08', '2022-09', '2022-10', '2022-11', '2022-12']

In [24]:
# 先把處理好的資料(dataframe)放到 list 中，最後在合併
def combine_all_csv_file(file_path,year_month):
    dfs = []

    for i in range(len(file_path)):
        df = pd.read_csv(file_path[i])
        # 刪掉第一個 row 
        df = df.drop(df.index[0])
        df['觀測站'] = '宜蘭縣'
        df['年份'] =  int(year_month[i][:year_month[i].find('-')])
        df['月'] = int(year_month[i][year_month[i].find('-')+1:])

        # Append the modified DataFrame to the list
        dfs.append(df)

    # Concatenate the list of DataFrames into a single DataFrame
    final_df = pd.concat(dfs, ignore_index=True)

    return final_df

final_weather_file_2021 = combine_all_csv_file(file_path_2021,year_month_2021)
final_weather_file_2022 = combine_all_csv_file(file_path_2022,year_month_2022)

In [25]:
final_weather_file_2021.tail(4)

,觀測時間(day),測站氣壓(hPa),海平面氣壓(hPa),測站最高氣壓(hPa),測站最高氣壓時間(LST),測站最低氣壓(hPa),測站最低氣壓時間(LST),氣溫(℃),最高氣溫(℃),最高氣溫時間(LST),...,地溫0cm,地溫5cm,地溫10cm,地溫20cm,地溫30cm,地溫50cm,地溫100cm,觀測站,年份,月
361,28,1023.9,1024.9,1027.5,2021/12/28 00:01:00,1021.5,2021/12/28 14:09:00,16.2,20.8,2021/12/28 13:31:00,...,16.5,17.1,17.1,18.3,17.2,18.4,21.1,宜蘭縣,2021,12
362,29,1021.8,1022.8,1024.2,2021/12/29 22:30:00,1020.0,2021/12/29 14:51:00,18.3,23.8,2021/12/29 12:26:00,...,17.4,17.8,17.8,18.6,17.7,18.5,20.9,宜蘭縣,2021,12
363,30,1026.1,1027.1,1027.9,2021/12/30 20:46:00,1023.7,2021/12/30 03:09:00,15.7,17.7,2021/12/30 00:01:00,...,16.4,17.4,17.7,18.9,17.9,18.6,20.8,宜蘭縣,2021,12
364,31,1026.6,1027.6,1028.2,2021/12/31 08:41:00,1025.0,2021/12/31 14:46:00,15.1,16.6,2021/12/31 10:35:00,...,15.8,16.7,16.9,18.4,17.2,18.3,20.8,宜蘭縣,2021,12

In [26]:
final_weather_file_2022.tail(4)

,觀測時間(day),測站氣壓(hPa),海平面氣壓(hPa),測站最高氣壓(hPa),測站最高氣壓時間(LST),測站最低氣壓(hPa),測站最低氣壓時間(LST),氣溫(℃),最高氣溫(℃),最高氣溫時間(LST),...,地溫0cm,地溫5cm,地溫10cm,地溫20cm,地溫30cm,地溫50cm,地溫100cm,觀測站,年份,月
361,28,1023.9,1024.9,1025.8,2022/12/28 21:05:00,1021.9,2022/12/28 14:07:00,15.4,16.5,2022/12/28 11:26:00,...,15.1,15.7,15.7,16.3,15.4,16.1,19.0,宜蘭縣,2022,12
362,29,1024.4,1025.4,1025.7,2022/12/29 09:12:00,1022.7,2022/12/29 14:36:00,15.7,16.6,2022/12/29 12:52:00,...,15.4,16.0,15.9,16.4,15.6,16.2,18.9,宜蘭縣,2022,12
363,30,1024.9,1025.9,1026.5,2022/12/30 20:30:00,1022.4,2022/12/30 14:14:00,16.4,17.7,2022/12/30 12:21:00,...,16.0,16.6,16.4,16.7,16.0,16.3,18.8,宜蘭縣,2022,12
364,31,1025.3,1026.3,1027.2,2022/12/31 09:32:00,1024.1,2022/12/31 14:47:00,16.0,16.9,2022/12/31 12:22:00,...,15.9,16.6,16.5,17.0,16.3,16.5,18.7,宜蘭縣,2022,12

In [27]:
print(final_weather_file_2021.shape)

(365, 45)

# 計算那天是第幾天 (後面沒有用到)

In [28]:
final_weather_file_2021['day_of_year'] = -1
final_weather_file_2022['day_of_year'] = -1

In [29]:
print(final_weather_file_2021.shape)

(365, 46)

In [30]:
from datetime import datetime
def to_day_of_yeaer(row):
    
    specified_date = datetime(row['年份'], row['月'], int(row['觀測時間(day)']))
    day_of_yearr = specified_date.timetuple().tm_yday
    return day_of_yearr

final_weather_file_2021['day_of_year'] = final_weather_file_2021.apply(to_day_of_yeaer, axis=1)
final_weather_file_2022['day_of_year'] = final_weather_file_2022.apply(to_day_of_yeaer, axis=1)

In [31]:
print(final_weather_file_2021.shape)
print(final_weather_file_2022.shape)

(365, 46)
(365, 46)

In [32]:
final_weather_file_2021.to_csv('all_2021宜蘭_weather_file.csv', index=False)
final_weather_file_2022.to_csv('all_2022宜蘭_weather_file.csv', index=False)

# clear version

In [1]:
import pandas as pd
import numpy as np
import os
import csv
from datetime import datetime

In [2]:
def complete_path(dirpath):
    paths = []
    for f in os.listdir(dirpath):
        fullpath = os.path.join(dirpath,f)
        paths.append(fullpath)
    return paths

def get_date_from_filename(dirpath):
    csv_file_names_without_csv = []

    for i in dirpath:
        csv_file_names_without_csv.append(i[i.find('-20')+1:i.find('.')])
    return csv_file_names_without_csv

def combine_all_csv_file(file_path,year_month):
    dfs = []

    for i in range(len(file_path)):
        df = pd.read_csv(file_path[i])
        # 刪掉第一個 row 
        df = df.drop(df.index[0])
        df['觀測站'] = '宜蘭縣'
        df['year'] =  int(year_month[i][:year_month[i].find('-')])
        df['month'] = int(year_month[i][year_month[i].find('-')+1:])

        # Append the modified DataFrame to the list
        dfs.append(df)

    # Concatenate the list of DataFrames into a single DataFrame
    final_df = pd.concat(dfs, ignore_index=True)
    return final_df

def to_day_of_yeaer(row):
    specified_date = datetime(row['year'], row['month'], int(row['觀測時間(day)']))
    day_of_yearr = specified_date.timetuple().tm_yday
    return day_of_yearr

In [6]:
dirpath = r"2017-宜蘭-觀測站"
file_path = complete_path(dirpath)

In [7]:
year_month = get_date_from_filename(file_path)
print(year_month[0])

2017-1

In [8]:
final_weather_file = combine_all_csv_file(file_path,year_month)

In [14]:
final_weather_file

,Unnamed: 0_level_0,press,press.1,press.2,press.3,press.4,press.5,Temperature,Temperature.1,Temperature.2,...,日最高紫外線指數,日最高紫外線指數時間(LST),總雲量(0~10),地溫0cm,地溫5cm,地溫10cm,地溫20cm,地溫30cm,地溫50cm,地溫100cm
0,ObsTime,StnPres,SeaPres,StnPresMax,StnPresMaxTime,StnPresMin,StnPresMinTime,Temperature,T Max,T Max Time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1021.2,1022.2,1024.0,2017/01/01 08:02:00,1018.9,2017/01/01 15:01:00,20.5,24.5,2017/01/01 12:40:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1019.1,1020.0,1020.7,2017/01/02 09:03:00,1017.6,2017/01/02 14:03:00,21.0,25.6,2017/01/02 12:29:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1019.3,1020.3,1021.3,2017/01/03 09:19:00,1017.6,2017/01/03 14:34:00,20.5,21.1,2017/01/03 08:41:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1017.4,1018.4,1019.9,2017/01/04 09:07:00,1015.1,2017/01/04 14:34:00,21.7,26.1,2017/01/04 14:25:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371,26,1009.5,1010.4,1011.3,2017/09/26 09:05:00,1008.1,2017/09/26 14:32:00,29.5,34.0,2017/09/26 13:59:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
372,27,1008.1,1009.0,1009.5,2017/09/27 08:42:00,1006.3,2017/09/27 14:21:00,29.8,34.5,2017/09/27 13:13:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
373,28,1009.5,1010.4,1012.4,2017/09/28 23:49:00,1007.9,2017/09/28 02:27:00,29.1,33.2,2017/09/28 10:23:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
374,29,1013.6,1014.5,1016.7,2017/09/29 21:31:00,1010.5,2017/09/29 03:39:00,26.5,30.0,2017/09/29 09:57:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
375,30,1014.7,1015.6,1016.5,2017/09/30 00:01:00,1013.2,2017/09/30 14:40:00,27.6,32.3,2017/09/30 12:25:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
final_weather_file.to_csv('all_2020宜蘭_weather_file.csv', index=False)

# using all function 
you just input the "year" in "complete" function it will generate that year's weather information in one csv , but this only "宜蘭-觀測站"

In [10]:
def complete(year):
    dirpath = str(year)+"-宜蘭-觀測站"
    file_path = complete_path(dirpath)
    year_month = get_date_from_filename(file_path)
    final_weather_file = combine_all_csv_file(file_path,year_month)
    # final_weather_file['day_of_year'] = final_weather_file.apply(to_day_of_yeaer, axis=1)
    file_name = "all_"+ str(year) + "宜蘭_weather_file.csv"
    # change colums's name
    new_columns = {'觀測時間(day)': 'day'}
    final_weather_file = final_weather_file.rename(columns=new_columns)
    final_weather_file['day'] = final_weather_file['day'].astype(int)
    return final_weather_file

# combine all years

In [ ]:
years = [2018,2019,2020,2021,2022]
dfs = []
for i in years:
    dfs.append(complete(i))

merged_df = pd.concat(dfs, ignore_index=True)
merged_df.to_csv('all_weather_data.csv', index=False)

In [5]:
merged_df.shape

NameError: name 'merged_df' is not defined

# using 爬蟲去抓資料 會和手動去抓的資料有一些不一樣的處理方法

In [88]:
df = pd.read_csv(r'2017-宜蘭-觀測站\467080-2017-1.csv')
df.head(1)

,Unnamed: 0_level_0,press,press.1,press.2,press.3,press.4,press.5,Temperature,Temperature.1,Temperature.2,...,UVI,UVI.1,Cloud,Soil,Soil.1,Soil.2,Soil.3,Soil.4,Soil.5,Soil.6
0,觀測時間 (day),測站氣壓 (hPa),海平面氣壓 (hPa),測站最高氣壓 (hPa),測站最高氣壓時間 (LST),測站最低氣壓 (hPa),測站最低氣壓時間 (LST),氣溫 (℃),最高氣溫 (℃),最高氣溫時間 (LST),...,日最高紫外線指數,日最高紫外線指數時間 (LST),總雲量 (0~10),地溫0cm,地溫5cm,地溫10cm,地溫20cm,地溫30cm,地溫50cm,地溫100cm

In [89]:
df.iloc[1]

Unnamed: 0_level_0           ObsTime
press                        StnPres
press.1                      SeaPres
press.2                   StnPresMax
press.3               StnPresMaxTime
press.4                   StnPresMin
press.5               StnPresMinTime
Temperature              Temperature
Temperature.1                  T Max
Temperature.2             T Max Time
Temperature.3                  T Min
Temperature.4             T Min Time
Dew Point               Td dew point
RH                                RH
RH.1                           RHMin
RH.2                       RHMinTime
WS/WD                             WS
WS/WD.1                           WD
WS/WD.2                       WSGust
WS/WD.3                       WDGust
WS/WD.4                    WGustTime
Precp                          Precp
Precp.1                    PrecpHour
Precp.2                   PrecpMax10
Precp.3               PrecpMax10Time
Precp.4                   PrecpMax60
Precp.5               PrecpMax60Time
SunShine                    SunShine
SunShine.1              SunshineRate
SunShine.2                  GloblRad
Visibility                  VisbMean
Evaperation                    EvapA
UVI                          UVI Max
UVI.1                   UVI Max Time
Cloud                   Cloud Amount
Soil                       TxSoil0cm
Soil.1                     TxSoil5cm
Soil.2                    TxSoil10cm
Soil.3                    TxSoil20cm
Soil.4                    TxSoil30cm
Soil.5                    TxSoil50cm
Soil.6                   TxSoil100cm
Name: 1, dtype: object

In [90]:
df.iloc[0]

Unnamed: 0_level_0             觀測時間 (day)
press                          測站氣壓 (hPa)
press.1                       海平面氣壓 (hPa)
press.2                      測站最高氣壓 (hPa)
press.3                    測站最高氣壓時間 (LST)
press.4                      測站最低氣壓 (hPa)
press.5                    測站最低氣壓時間 (LST)
Temperature                        氣溫 (℃)
Temperature.1                    最高氣溫 (℃)
Temperature.2                最高氣溫時間 (LST)
Temperature.3                    最低氣溫 (℃)
Temperature.4                最低氣溫時間 (LST)
Dew Point                        露點溫度 (℃)
RH                               相對溼度 (%)
RH.1                           最小相對溼度 (%)
RH.2                       最小相對溼度時間 (LST)
WS/WD                            風速 (m/s)
WS/WD.1                    風向 (360degree)
WS/WD.2                       最大瞬間風 (m/s)
WS/WD.3               最大瞬間風風向 (360degree)
WS/WD.4                   最大瞬間風風速時間 (LST)
Precp                            降水量 (mm)
Precp.1                       降水時數 (hour)
Precp.2                     最大十分鐘降水量 (mm)
Precp.3                最大十分鐘降水量起始時間 (LST)
Precp.4                    最大六十分鐘降水量 (mm)
Precp.5               最大六十分鐘降水量起始時間 (LST)
SunShine                      日照時數 (hour)
SunShine.1                        日照率 (%)
SunShine.2                  全天空日射量 (MJ/㎡)
Visibility                       能見度 (km)
Evaperation                    A型蒸發量 (mm)
UVI                              日最高紫外線指數
UVI.1                    日最高紫外線指數時間 (LST)
Cloud                          總雲量 (0~10)
Soil                                地溫0cm
Soil.1                              地溫5cm
Soil.2                             地溫10cm
Soil.3                             地溫20cm
Soil.4                             地溫30cm
Soil.5                             地溫50cm
Soil.6                            地溫100cm
Name: 0, dtype: object

In [91]:
# Drop the first row
df = df.drop(1)

# Set the second row as the new header
df.columns = df.iloc[0]
df = df[1:]

In [92]:
df.head(3)

,觀測時間 (day),測站氣壓 (hPa),海平面氣壓 (hPa),測站最高氣壓 (hPa),測站最高氣壓時間 (LST),測站最低氣壓 (hPa),測站最低氣壓時間 (LST),氣溫 (℃),最高氣溫 (℃),最高氣溫時間 (LST),...,日最高紫外線指數,日最高紫外線指數時間 (LST),總雲量 (0~10),地溫0cm,地溫5cm,地溫10cm,地溫20cm,地溫30cm,地溫50cm,地溫100cm
2,1,1021.2,1022.2,1024.0,2017/01/01 08:02:00,1018.9,2017/01/01 15:01:00,20.5,24.5,2017/01/01 12:40:00,...,6,2017/01/01 12:00:00,9.0,20.9,21.3,21.2,20.7,20.4,21.0,22.0
3,2,1019.1,1020.0,1020.7,2017/01/02 09:03:00,1017.6,2017/01/02 14:03:00,21.0,25.6,2017/01/02 12:29:00,...,6,2017/01/02 12:00:00,3.7,22.5,22.2,22.1,21.4,21.0,21.5,22.0
4,3,1019.3,1020.3,1021.3,2017/01/03 09:19:00,1017.6,2017/01/03 14:34:00,20.5,21.1,2017/01/03 08:41:00,...,2,2017/01/03 14:00:00,9.2,20.8,21.6,22.2,21.7,21.5,22.5,22.0

In [93]:

df.columns

Index(['觀測時間 (day)', '測站氣壓 (hPa)', '海平面氣壓 (hPa)', '測站最高氣壓 (hPa)',
       '測站最高氣壓時間 (LST)', '測站最低氣壓 (hPa)', '測站最低氣壓時間 (LST)', '氣溫 (℃)',
       '最高氣溫 (℃)', '最高氣溫時間 (LST)', '最低氣溫 (℃)', '最低氣溫時間 (LST)', '露點溫度 (℃)',
       '相對溼度 (%)', '最小相對溼度 (%)', '最小相對溼度時間 (LST)', '風速 (m/s)',
       '風向 (360degree)', '最大瞬間風 (m/s)', '最大瞬間風風向 (360degree)',
       '最大瞬間風風速時間 (LST)', '降水量 (mm)', '降水時數 (hour)', '最大十分鐘降水量 (mm)',
       '最大十分鐘降水量起始時間 (LST)', '最大六十分鐘降水量 (mm)', '最大六十分鐘降水量起始時間 (LST)',
       '日照時數 (hour)', '日照率 (%)', '全天空日射量 (MJ/㎡)', '能見度 (km)', 'A型蒸發量 (mm)',
       '日最高紫外線指數', '日最高紫外線指數時間 (LST)', '總雲量 (0~10)', '地溫0cm', '地溫5cm',
       '地溫10cm', '地溫20cm', '地溫30cm', '地溫50cm', '地溫100cm'],
      dtype='object', name=0)

In [115]:
def complete_path(dirpath):
    paths = []
    for f in os.listdir(dirpath):
        fullpath = os.path.join(dirpath,f)
        paths.append(fullpath)
    return paths

def get_date_from_filename(dirpath):
    csv_file_names_without_csv = []

    for i in dirpath:
        csv_file_names_without_csv.append(i[i.find('-20')+1:i.find('.')])
    return csv_file_names_without_csv

def web_crawler_combine_all_csv_file(file_path,year_month):
    dfs = []

    for i in range(len(file_path)):
        df = pd.read_csv(file_path[i])
        # 刪掉第一個 row 
        # Drop the first row
        df = df.drop(1)

        # Set the second row as the new header
        df.columns = df.iloc[0]
        df = df[1:]
        df.columns = df.columns.str.replace(' ', '')

        df['觀測站'] = '宜蘭縣'
        df['year'] =  int(year_month[i][:year_month[i].find('-')])
        df['month'] = int(year_month[i][year_month[i].find('-')+1:])

        # Append the modified DataFrame to the list
        dfs.append(df)

    # Concatenate the list of DataFrames into a single DataFrame
    final_df = pd.concat(dfs, ignore_index=True)
    return final_df

def hand_get_combine_all_csv_file(file_path,year_month):
    dfs = []

    for i in range(len(file_path)):
        df = pd.read_csv(file_path[i])
        # 刪掉第一個 row 
        df = df.drop(df.index[0])
        df['觀測站'] = '宜蘭縣'
        df['year'] =  int(year_month[i][:year_month[i].find('-')])
        df['month'] = int(year_month[i][year_month[i].find('-')+1:])

        # Append the modified DataFrame to the list
        dfs.append(df)

    # Concatenate the list of DataFrames into a single DataFrame
    final_df = pd.concat(dfs, ignore_index=True)
    return final_df


# def to_day_of_yeaer(row):
#     specified_date = datetime(row['year'], row['month'], int(row['觀測時間(day)']))
#     day_of_yearr = specified_date.timetuple().tm_yday
#     return day_of_yearr

In [116]:
def complete(year):
    dirpath = str(year)+"-宜蘭-觀測站"
    file_path = complete_path(dirpath)
    year_month = get_date_from_filename(file_path)

    if(year==2017): #because using when using the web crawler the result may have some different so we have to separate
        final_weather_file = web_crawler_combine_all_csv_file(file_path,year_month)
    else:
        final_weather_file = hand_get_combine_all_csv_file(file_path,year_month)

    # final_weather_file['day_of_year'] = final_weather_file.apply(to_day_of_yeaer, axis=1)
    file_name = "all_"+ str(year) + "宜蘭_weather_file.csv"
    # change colums's name
    new_columns = {'觀測時間(day)': 'day'}
    final_weather_file = final_weather_file.rename(columns=new_columns)
    final_weather_file['day'] = final_weather_file['day'].astype(int)
    return final_weather_file

In [117]:
years = [2017,2018,2019,2020,2021,2022]
dfs = []
for i in years:
    dfs.append(complete(i))

merged_df = pd.concat(dfs, ignore_index=True)
merged_df.to_csv('all_weather_data.csv', index=False)

In [118]:
merged_df.shape

(2191, 45)